export const sampleFoods = [
  {
    id: 1,
    name: "Spaghetti Carbonara",
    cookTime: "30 minutes",
    price: 12.99,
    favorite: true,
    origin: "Italian",
    stars: 4.5,
    tags: ['FastFood', 'Pizza', 'Lunch'],
    imageUrl: "sample-1.jpg",
  },
  {
    id: 2,
    name: "Sushi Roll",
    cookTime: "15 minutes",
    price: 18.99,
    favorite: false,
    origin: "Japanese",
    stars: 4.7,
    tags: ['SlowFood', 'Lunch'],
    imageUrl: "sample-2.jpg",
  },
  {
    id: 3,
    name: "Chicken Tikka Masala",
    cookTime: "45 minutes",
    price: 14.99,
    favorite: true,
    origin: "Indian",
    stars: 4.8,
    tags: ['FastFood', 'Hamburger'],
    imageUrl: "sample-3.jpg",
  },
  {
    id: 4,
    name: "Hamburger",
    cookTime: "20 minutes",
    price: 8.99,
    favorite: true,
    origin: "American",
    stars: 4.3,
    tags: ['FastFood', 'Fry'],
    imageUrl: "sample-4.jpg",
  },
  {
    id: 5,
    name: "Pad Thai",
    cookTime: "25 minutes",
    price: 10.99,
    favorite: false,
    origin: "Thai",
    stars: 4.6,
    tags: ['SlowFood', 'Soup'],
    imageUrl: "sample-5.JPG",
  },
  {
    id: 6,
    name: "Margherita Pizza",
    cookTime: "15 minutes",
    price: 9.99,
    favorite: false,
    origin: "Italian",
    stars: 4.4,
    tags: ['FastFood', 'Pizza', 'Lunch'],
    imageUrl: "sample-6.jpg",
  },
  {
    id: 7,
    name: "Sushi Sashimi",
    cookTime: "10 minutes",
    price: 22.99,
    favorite: true,
    origin: "Japanese",
    stars: 4.9,
    tags: ['FastFood', 'Pizza', 'Lunch'],
    imageUrl: "sample-7.jpg",
  },
];


export const sampleTags = [
  {name: 'All' ,count: 7},
  {name: 'FastFood', count: 5},
  {name: 'Pizza', count: 3},
  {name: 'Lunch', count: 4},
  {name: 'SlowFood', count: 2},
  {name: 'Hamburger', count: 1},
  {name: 'Fry', count: 1},
  {name: 'Soup', count: 1}
]